project:
  type: website
  output-dir: docs
  

website:
  title: "My Personal Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - UsefulLinks.qmd

format:
  html:
    theme: "litera"
    css: styles.css
    toc: true

editor: visual

